### PR TITLE
added schemas

### PR DESCRIPTION
**Pull request by wanderer**
this adds a scheme template for each type. I use it when generating new AST nodes. Might be usefully to others

### CODE REVIEW

**Comment by drom** [comment]
@wanderer can you use Json Schema for that?
http://spacetelescope.github.io/understanding-json-schema/UnderstandingJSONSchema.pdf

**Comment by wanderer** [comment]
maybe! let me try

**Comment by wanderer** [comment]
@drom wanted to report back on Json schema. Its nice, but what I want to with the schema is not validate, but generate. And i still have found a nice way to generate an object from a schema. #futuremoduleidea

**Comment by drom** [comment]
@wanderer how is your schema better then visitor key?

**Comment by wanderer** [comment]
It serves a different purposes. Visitor keys are good for traversing. But
when generating you need to know whether a key is an array or not

**Comment by drom** [comment]
We have data structure for this: https://github.com/drom/wast-codegen/blob/master/bin/generator.js#L30-L37

**Pull request merged**
